### ISSUE TITLE
include the skrub wheel in the built documentation

### ISSUE THREAD

**Issue by jeromedockes** [skrub-data/skrub#1029]
at the moment for jupyterlite we hardcode the link to a particular skrub version on pypi:

https://github.com/skrub-data/skrub/blob/b5962f705ee980e83ec07fc4eda0876b0ebdac6f/doc/conf.py#L386

however that version may not be the right one, and the right one may not be on pypi yet (eg when running the examples for the dev/ documentation, or when we make a release there is a chicken-egg problem:we would like to write the correct pypi link before releasing, but it doesn't exist before the release)

it would be better to build the wheel as a part of building the documentation and include it as a static asset. then in jupyterlite we would pip install the wheel that is in the same directory of the current site rather than a hardcoded one from pypi

**Comment by GaelVaroquaux** [comment]
It would help indeed, and having a nightly as part of the dev docs would be amazing!

**Comment by jeromedockes** [comment]
https://github.com/jupyterlite/jupyterlite/issues/1023

**Comment by jeromedockes** [comment]
after discussing a bit it's probably not worth the effort; installing from pypi is good enough for scikit-learn so it's probably good enough for skrub as well :)
