### ISSUE TITLE
Indexing failures on some of our pages

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#1039]
![Screenshot_20240812_144559_Chrome](https://github.com/user-attachments/assets/f6ff27a4-e157-43dc-afb2-9b23825e45d1)

Google is telling me it has indexing failures on pages that it used to be able to index.
Discontinuities in URLs is a bad thing for us, as it will decrease our Google rank, and we need this currently

**Comment by glemaitre** [comment]
This is possible to create a redirection with sphinx:

https://github.com/scikit-learn/scikit-learn/blob/main/doc/conf.py#L422-L458

I think this is worth redirecting to the new similar page.

**Comment by Vincent-Maladiere** [comment]
Did #1041 solve this, @GaelVaroquaux?

**Comment by Vincent-Maladiere** [comment]
I think this is solved, let's reopen another issue with more recent SEO results is that were not the case
