### ISSUE TITLE
TableReport Stats doesn't display nunique Integers

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#1070]
### Describe the bug

Linked to https://github.com/skrub-data/skrub/issues/1052

Integer values should have a cardinality displayed in "Stats". Integers can represent IDs or other discrete quantities.

### Steps/Code to Reproduce

NA

### Expected Results

NA

### Actual Results

NA

### Versions

```shell
NA
```

**Comment by jeromedockes** [comment]
yes ATM it does not check cardinality for numeric columns. we could do it for integers and replace the histogram with a bar plot when the cardinality is low
