### ISSUE TITLE
More details on the contributing section

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#1071]
### Describe the issue linked to the documentation

Mention pytest and pre-commit

See https://github.com/skrub-data/skrub/pull/1069#issuecomment-2345024817

**Comment by Shree7676** [comment]
Suggestion:
on this perticular https://skrub-data.org/stable/CONTRIBUTING.html#building-the-documentation site
when we click on headings it takes you to the top table. I don't feel that's good if its taking to some other page or some other area which contains more detail then it makes sense 
So I feel we should just keep it plain heading without link like other pages
(Idealogy : People usually click when they need extra details but if its taking you back to from where it started it doesn't feel good)

**Comment by jeromedockes** [comment]
fixed in #1084
