### ISSUE TITLE
TableReport ENH: tighter layout when nothing selected

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#1076]
As you know, I'm always trying to have tighter layouts (this is really important because it reduces the scrolling in GUIs/IDEs).

Playing with the TableReport (very very cool), I'm thinking that we could move the green hint that appears when nothing is selected to put it where the key bindings appear. We might have to make the sentence a bit shorter, and I suggest "Click cells for info on columns"

The benefit would be less vertical scrolling by default. The drawback would be a "jump" in vertical height when the selected cell appears. I think that it's worth the cost, as we get jumps anyhow with the column vignette appearing below.

**Comment by jeromedockes** [comment]
discussed IRL at the weekly skrub meeting: there are a couple of other tweaks we want to apply first

- deleting the stdout ("processing column x/ y") once the report is displayed
- making sure we don't use a bigger font than the parent
- seeing if there are places where we can remove a bit of padding without making the report too crowded
- displaying one fewer rows by default? (not mentioned in meeting, I just thought of  it now)

once we have done those, we will consider the trade-off of saving space vs having a jump when we click a cell, which as you mention can be disconcerting as it can cause the thing you just clicked to skip from under your mouse

**Comment by jeromedockes** [comment]
IIRC we decided in a real-life meeting that given other changes we have made to the report (some of them outline in my comment above) it is not worth causing the table to jump from under the mouse when we select a cell to save this space.

Please reopen if I misremember!

**Comment by GaelVaroquaux** [comment]
> Please reopen if I misremember!

Nope, that was a good summary. Thank you!
