### ISSUE TITLE
Add a `DropEmpty` flag to `tabular_learner`

### ISSUE THREAD

**Issue by rcap107** [skrub-data/skrub#1110]
### Problem Description

I am currently working with tables that may contain columns that contain only null/missing values. I also need to perform imputation (with sklearn's SimpleImputer) over all the columns to fill nulls there. 

A simplified version of my pipeline is this:

```py
import polars as pl
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from skrub import TableVectorizer


df_ = pl.DataFrame({"a": [1,2,3], "empty":[None, None, None]})

num_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="mean", keep_empty_features=False)),
        ("scaler", StandardScaler()),
    ]
)

# Transformer for high cardinality categorical features 
high_card_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent", keep_empty_features=False),
        ),
        ("onehot_encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ],
)

low_card_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent", keep_empty_features=False),
        ),
        (
            "onehot_encoder",
            OneHotEncoder(handle_unknown="ignore", sparse_output=False),
        ),
    ],
)
preprocessor = TableVectorizer(
    low_cardinality=low_card_transformer,
    high_cardinality=high_card_transformer,
    numeric=num_transformer,
)

preprocessor.fit_transform(df_)

```

This raises an exception on column `empty` because no values are found. 

### Feature Description

Rather than raising an exception at the end of the pipeline, which makes debugging more complex (the error messages were less than helpful), it would be nice to have an automated check of all columns before any operation is done to screen for empty columns. 

Some possible improvements could be:
- A warning to the user ("Column something something is empty") 
- Dropping the column immediately
- Dropping the column if the fraction of null values is larger than a given threshold

This should also be added to the `tabular_learner` so that if such a situation occurs, it doesn't fail for some weird reason. 

### Alternative Solutions

Setting the SimpleImputer parameter `keep_empty_features=True` seems to fix the problem (or at least, the code does not fail anymore). Null values are replaced by 0.

**Comment by jeromedockes** [comment]
thanks @rcap107 ! I think it is a good idea to drop completely empty features by default in tablevectorizer and tabular_learner

should we also drop constant features?

**Comment by rcap107** [comment]
I think constant features should be kept, because even if they may not be useful for learning, they might still be useful for the user in some way.

I am thinking of a situation in which the user has multiple tables that are distinguished by a specific constant column, and that once they are concatenated the feature becomes meaningful. I don't know if that's something that should pass through TableVectorizer, but it's a possible case where I can see constant features being useful. 

There could definitely be a flag for dropping them if needed, but it should be False by default imo

**Comment by Vincent-Maladiere** [comment]
> I am thinking of a situation in which the user has multiple tables that are distinguished by a specific constant column, and that once they are concatenated the feature becomes meaningful. I don't know if that's something that should pass through TableVectorizer, but it's a possible case where I can see constant features being useful.

Could the same argument be made for empty features? If some tables had an empty column while others had values, you wouldn't want to drop that column.

So, we could display a warning by default, as you suggested, and optionally removing empty columns. This behavior could be controlled with a single argument `only_nan_columns='warn'`, `'drop'` or `'raise'` for instance.
