### ISSUE TITLE
Consider remerging the API list into one page

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#1118]
The API page has recently been broken down into many small pages.

The drawback of such division is that one needs to know on which page a given function is going to be listed to access its documentation (and that's not obvious at all, even myself I get it wrong).
Relatedly, "ctrl-f" is no longer very useful. My typical pattern when I don't find what I'm looking for is to go to the API page and "ctr-f" for it.

I would push for remerging the pages into a single page.

**Comment by Vincent-Maladiere** [comment]
To ensure I understand the issue, you can still ctr-f on the top-level page skrub-data.org/dev/reference/index.html, correct? So, you want to remove the intermediate API pages when clicking on a section, and bring these together instead of the top-level list of links?

**Comment by GaelVaroquaux** [comment]
> To ensure I understand the issue, you can still ctr-f on the top-level page skrub-data.org/dev/reference/index.html, correct?

Good point indeed.

What happened was that I clicked on the section, didn't find what I want, then was lost.

But indeed, the problem is less pronounced than I thought. Maybe we can ignore this issue. I don't know.

> So, you want to remove the intermediate API pages when clicking on a section, and bring these together instead of the top-level list of links?

This was my suggestion.

**Comment by Vincent-Maladiere** [comment]
I guess it makes sense to simplify the hierarchy and remove the intermediary levels. This way people won't get lost and will save a few clicks.
