### ISSUE TITLE
Enhance Datetime Features with Cyclical Encoding to Preserve Metric

### ISSUE THREAD

**Issue by mmartinb75** [skrub-data/skrub#1127]
### Problem Description
The library currently extracts datetime features like hour, day, month, etc., but doesn't account for their cyclical nature. This can lead to models misinterpreting the relationship between time features. For example, the model might treat hour 23 as being far from hour 0, while in reality, they are adjacent.

### Feature Description
Add two new features for each extracted datetime component (second, minute, hour, day, month, and week) using sine and cosine transformations. The frequencies for each component will match its cyclical property: 60 for second and minute, 24 for hour,  the actual number of days in the given month for day, and 12 for month.

**Comment by rcap107** [comment]
Related to #907

**Comment by jeromedockes** [comment]
thanks @mmartinb75 that's a great discussion and as @rcap107  mentioned it is being discussed in #907 . basically the discussion has sort of stalled on the topic of using sin or splines, but it would be great to revive it and add this.

I will close this issue to avoid duplicating the conversation but I'll link your comment from there and please feel free to engage in the discussion in #907 !

**Comment by mmartinb75** [comment]
right!!. thanks a lot @jeromedockes
