### ISSUE TITLE
TimeDelta64DType treated as category by the TableReport

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#1132]
### Describe the bug

This is somewhat niche, but TableReport treats TimeDelta64DType as discrete categories, while it's a continuous quantity as DateTime64DType.

### Steps/Code to Reproduce

```python
import pandas as pd
from skrub import TableReport

TableReport(
    pd.to_timedelta([20, 40], unit="D").to_frame()
)
```

### Expected Results

A histogram distribution

### Actual Results

A value counts distribution

### Versions

```shell
dev
```

**Comment by jeromedockes** [comment]
I guess we need to special case timedeltas, inspect the range of values to decide on a time resolution and cast to float to plot a histogram
