### ISSUE TITLE
Clip range of histograms in TableReport

### ISSUE THREAD

**Issue by jeromedockes** [skrub-data/skrub#1155]
This has been reported in a few places: when a column contains outliers, the histogram plot produced by the tablereport is not very informative because the range is very wide and almost all the distribution is in the same bin. (it does help realize that there are outliers, which is good)

It would be better to remove outliers before plotting the histogram so we can see more detail, _but_ in this case we need to come up with a way to make it obvious that outliers had to be removed and convey how many there were.

the "outlier detection" would have to be very cheap, for example we could do something similar to what box plots do (clip at some percentile's position offset by a factor of the inter-percentile range)

**Comment by Vincent-Maladiere** [comment]
We should also think of a way to display these outliers, even if they are put in a single bin at the edges (whose color could be different?)
