### ISSUE TITLE
Interaction between `TableReport` and `matplotlib`

### ISSUE THREAD

**Issue by glemaitre** [skrub-data/skrub#1171]
Given the following code blocks:

```python
# %%
import skrub

# %%
from sklearn.datasets import load_iris
data, target = load_iris(return_X_y=True, as_frame=True)
TableReport(data)

# %%
data["sepal length (cm)"].plot.hist()
```

We expect (in a notebook or vs code) that running those cell will end-up showing the report and the histogram plot. However, the later cell requires a `plt.show()` to show the plot. This is not the behaviour when not patching the display.

Also it seems that if we intend a first plot, then the interaction with matplotlib does not happen:

```python
# %%
import skrub

# %%
from sklearn.datasets import load_iris
data, target = load_iris(return_X_y=True, as_frame=True)

# %%
data["sepal length (cm)"].plot.hist()

# %%
skrub.TableReport(data)

# %%
data["sepal length (cm)"].plot.hist()
```

I'm wondering if this is something expected?

**Comment by jeromedockes** [comment]
> I'm wondering if this is something expected?

:joy: :sweat_smile: 

thanks for reporting I'll look into it

**Comment by jeromedockes** [comment]
maybe relevant: https://github.com/matplotlib/matplotlib/issues/25041

**Comment by jeromedockes** [comment]
also reported here: https://github.com/matplotlib/matplotlib/issues/26716

**Comment by glemaitre** [comment]
Interesting. At least there is a work around.

**Comment by jeromedockes** [comment]
the matplotlib context manager does not seem to do anything more complex than updating `matplotlib.rcParams` so we can do it ourselves, and by updating only the key we need it seems to fix the issue: #1172 

let me know if it works on your side :)

**Comment by Vincent-Maladiere** [comment]
FWIW, I can't reproduce @glemaitre issue on VSCode

**Comment by jeromedockes** [comment]
> FWIW, I can't reproduce @glemaitre issue on VSCode

interesting, thanks for trying it! in any case it should be fixed on the main branch now
