### ISSUE TITLE
Allow `tabular_learner("regression")`

### ISSUE THREAD

**Issue by jeromedockes** [skrub-data/skrub#1177]
### Problem Description

We can use `skrub.tabular_learner(estimator="regressor")` to use a default `HistGradientBoostingRegressor` as the final estimator of the pipeline.

I find myself typing `skrub.tabular_learner("regression")` more often than I would like :)
I think there is no ambiguity in this case and as a user rather than an error I would prefer skrub to accept "regression" as a synonym for "regressor" -- same for "classification"

### Feature Description

"regression" and "classification" would be accepted to mean "regressor" and "classifier" respectively

**Comment by mrastgoo** [comment]
I am working on it
