### ISSUE TITLE
Create examples for the column associations metrics

### ISSUE THREAD

**Issue by reshamas** [skrub-data/skrub#1181]
### Describe the issue linked to the documentation

https://skrub-data.org/stable/reference/generated/skrub.column_associations.html

Metrics:  
- Cramer’s V statistic
- other metrics

Working example from pandas:
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html
- can also find examples in skrub

**Comment by jeromedockes** [comment]
to recap what we said yesterday: the `column_associations` function is missing an "Examples" section in its docstring. It would be great to add a small example section to show generating the associations for a toy example dataframe, so users can see how to call it and what would be the shape and content of the output. something like

```
Examples
--------
>>> import pandas as pd
>>> from skrub import column_associations
>>> df = ...
>>> column_associations(df)
       ...
```

**Comment by jeromedockes** [comment]
I'll mark this one as completed: when more association metrics are added they will show up in the output of the example added in #1186 

When we add more metrics we will also update the documentation to include a short paragraph and wikipedia link for each.

To be continued in #1176  ...
