### ISSUE TITLE
Example 1: use DatetimeEncoder instead of isolating year

### ISSUE THREAD

**Issue by jovan-stojanovic** [skrub-data/skrub#341]
In [example 1](https://dirty-cat.github.io/stable/auto_examples/01_dirty_categories.html#sphx-glr-auto-examples-01-dirty-categories-py), we use the `year first hired` feature to predict wages. 

In the second part, when we use dirty_cat to encode variables, we may use the `DatetimeEncoder` instead of just passing through this variable. It is also possible not to drop the `date_first_hired`  variable and encode it instead.

To see what results this would give.

Also, would the SuperVectorizer (used in the second part) identify the `date_first_hired` column to be automatically encoded by the `DatetimeEncoder`? 
It does not at the moment for years.

**Comment by LilianBoulard** [comment]
I'm working on this

**Comment by GaelVaroquaux** [comment]
I see a benefit in applying the DatetimeEncoder to the `date_first_hired` column but not to the `year_first_hired` one, as a year does not need a complex transformation to be useful.

For this specific example, I'm not sure that we want to modify the first part to add the DatetimeEncoder. It would have the benefit of bringing the DatetimeEncoder to the attention of the reader, but it would make the code more complicated.

What could be really cool is if in the second part, the TableVectorizer could "do the right thing", which is probably detect that the `date_first_hired` column is a date and apply the DatetimeEncoder to it. That might be hard to do.
