### ISSUE TITLE
`pkg_ressources` is deprecated

### ISSUE THREAD

**Issue by LilianBoulard** [skrub-data/skrub#550]
Seen in `_check_dependencies.py`:
![image](https://user-images.githubusercontent.com/33222654/233378673-4168e6af-80fb-4f04-9b87-a546ce644a4a.png)

**Comment by Vincent-Maladiere** [comment]
cc @fcharras, who helped with the setup of `pkg_resources` :)

**Comment by fcharras** [comment]
It looks like it's a bug in latest `setuptools` release ? see https://stackoverflow.com/a/76044568 and https://github.com/pypa/pip/issues/11975

**Comment by fcharras** [comment]
IIRC, `pkg_resources` is indeed deprecated or at least its use is discouraged in projects, see [setuptools doc](https://setuptools.pypa.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources) . But what is supposed to be the replacement, [importlib](https://docs.python.org/3/library/importlib.html), does not embed the features that are needed to implement `check_dependencies` nor any other alternatives I'm aware of (or at least it did not at the time it was merged).
