### ISSUE TITLE
Example to do model selection with TableVectorizer

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#554]
We should make an example that does model selection with a pipeline that includes a TableVectorizer, to show the benefit of tuning jointly the preprocessing and the learner.

However, doing this example may reveal shortcomings in our design of the TableVectorizer. For instance, I realized that I cannot use and RandomSearchCV to set the dimensionality of the GapEncoder (because this dimensionality is not a parameter accessible at the level of the TableVectorizer). We might need to brainstorm a bit more.

**Comment by Vincent-Maladiere** [comment]
Solved by https://github.com/skrub-data/skrub/pulls?q=is%3Apr+sort%3Aupdated-desc
