### ISSUE TITLE
Benchmarks cleanup

### ISSUE THREAD

**Issue by jovan-stojanovic** [skrub-data/skrub#557]
The benchmarks are really confusing for newcomers: 
- **naming**: some start with the benchmark prefix and others don't (we should standardize)
- **scripts**: we say in the README that all benchmarks can be executed using a simple call from the terminal but this does not work for most.
- **functions**: some functions are reused from one benchmark script to the other, which is confusing so we might want to add those to the utils folder.

**Comment by LilianBoulard** [comment]
Solved by #574
