### ISSUE TITLE
Add jupyter-lite to our sphinx-gallery

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#625]
### Describe the issue linked to the documentation

As in scikit-learn example, we would like to have the yellow "jupyter-lite" button to launch using jupyterlite/javascript

https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html

### Suggest a potential alternative/fix

Sphinx-gallery has support for jupyterlite. It just needs to be configured (which can be hard).

Some inspiration can come from scikit-learn. Maybe @lesteve can help

**Comment by jovan-stojanovic** [comment]
Fixed with #633

**Comment by lesteve** [comment]
Nice :tada:
