### ISSUE TITLE
Outline for the main encoding example

### ISSUE THREAD

**Issue by LilianBoulard** [skrub-data/skrub#662]
(migrated from #657)

As discussed with Gaël, here is a proposed outline for the main encoding example. Please submit your suggestions!

- Start with a dirty dataset, probably employee_salaries
- First, use the TableVectorizer, just to say "with little trouble, it works ootb"
- Then go into what it did, and the internals (GapEncoder, DatetimeEncoder)
- Use the MinHashEncoder for a larger dataset (maybe the largest one we have)

Notes:
- Should we talk about the SimilarityEncoder?
- Should we introduce the problem of dirty categories in this notebook?
- We should integrate the [cross-validation example from](https://github.com/skrub-data/skrub/blob/3e312f9a41ff1e1fe4123e2af80ac93f15724b99/examples/encoding/grid_search_with_the_tablevectorizer.py) #546, but not sure where

cc @myungkim930

**Comment by GaelVaroquaux** [comment]
Answers:
- Mention SimilarityEncoder, but in the text, not code
- Mention dirty-categories briefly in text only
- Consider cross-validation in a section at the end. Consider also grid search
- Do feature interpretation also in the example in a section of itself
