### ISSUE TITLE
Add array-to-dummies preprocessor

### ISSUE THREAD

**Issue by coconutattitude** [skrub-data/skrub#717]
### Problem Description

Some tables have categories that are stored in one array in one variable. It can happen when the data is collected in time periods, for example, we have a table where rows are router users and the column is "ips to which the router connected during last 15 minutes" (example A). Or it could be a data taken from survey respondents that answered question "name all countries you have visited this year" (Example B). 
In example A we would have a pandas series "connected_ips" that for each row would have an array that would look like this:
[1234.1244, 1556.6666, 1998.1534, 1490.4444] 
In example B we would have a pandas series "visited countries" that for each row would have an array that would look like this:
["Basel", "Warsaw", "Paris", "Kijów"]

### Feature Description

A new feature, array2dummies preprocessor could take such columns, if they come as one string then evaluate them to python list, and then transform the values into dummies for each row. 
in Example A we would end up with 4 columns:  ip_1234.1244, ip_1556.6666, ip_1998.1534, ip_1490.4444 with 1 if the router had visited them and 0 if it didn't.
in Example B we could at first allow user to use either GapEncoder or MinHashEncoder and then make dummies, so we would end up with 4 columns: "visited_Basel", "visited_Warsaw", "visited_Paris", "visited_Kijów" also  with 1 if the respondent had visited them and 0 if he/she didn't.
the important part in the second example would be to allow user for use of the encoders already available in the Skrub.

### Additional Context

Many tables have categorical count data stored in inconvenient format - as lists in a dataframe "cell". In order to fit those data to the model, they need to be preprocessed. It would be great to have an automated way to do so, with an option to use Skrub's encoders.

**Comment by GaelVaroquaux** [comment]
This seems close to scikit-learn CountVectorizer

**Comment by Vincent-Maladiere** [comment]
Let's close this issue since `CountVectorizer` addresses the feature request.
