### ISSUE TITLE
Interactive examples for skrub

### ISSUE THREAD

**Issue by edublancas** [skrub-data/skrub#740]
Hi skrub team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a Binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor skrub with some computing power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by Vincent-Maladiere** [comment]
Hi @edublancas, thank you for your message. We already use Binder in our example, and it runs smoothly. What would be the benefits of using your Binder cluster? What would this entail in concrete terms?

**Comment by edublancas** [comment]
The shared, public binder cluster (mybinder.org) reduced capacity recently, which causes an uptick in errors: if there are no resources available, users won't be able to use it (see more [here](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f) and [here](https://discourse.jupyter.org/t/mybinder-org-reducing-capacity-unstable/19163))

Our cluster isn't public, so it doesn't have these capacity issues. Let me know what you think!

I enabled skrub in our cluster so you can take it for a spin: https://binder.ploomber.io/v2/gh/skrub-data/skrub/main

**Comment by Vincent-Maladiere** [comment]
How would we enable your cluster in our examples?

**Comment by edublancas** [comment]
Hi @Vincent-Maladiere. The change implies swapping the links from binder.org to our binder cluster. Unfortunately, we have already onboarded a few open-source projects and have no capacity. We might open new slots soon; I’ll contact you if that happens!
