### ISSUE TITLE
BUG DateTimeEncoder fails when `extract_until` is "year" or "month"

### ISSUE THREAD

**Issue by jeromedockes** [skrub-data/skrub#745]
### Describe the bug

raises an error during `fit` when those values are used

### Steps/Code to Reproduce

```python
from skrub import DatetimeEncoder

DatetimeEncoder(extract_until="year").fit([["2023-09-20"]])
```

### Expected Results

No error

### Actual Results

```
ValueError: <YearEnd: month=12> is a non-fixed frequency
```

### Versions

```shell
System:
    python: 3.11.5 (main, Aug 25 2023, 13:19:50) [GCC 11.4.0]
executable: /home/jerome/.virtualenvs/df/bin/python
   machine: Linux-6.2.0-32-generic-x86_64-with-glibc2.35

Python dependencies:
      sklearn: 1.3.0
          pip: 23.2.1
   setuptools: 65.5.0
        numpy: 1.25.2
        scipy: 1.11.2
       Cython: None
       pandas: 2.1.0
   matplotlib: 3.7.3
       joblib: 1.3.2
threadpoolctl: 3.2.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
    num_threads: 4
         prefix: libgomp
       filepath: /home/jerome/.virtualenvs/df/lib/python3.11/site-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 4
         prefix: libopenblas
       filepath: /home/jerome/.virtualenvs/df/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-5007b62f.3.23.dev.so
        version: 0.3.23.dev
threading_layer: pthreads
   architecture: Prescott

       user_api: blas
   internal_api: openblas
    num_threads: 4
         prefix: libopenblas
       filepath: /home/jerome/.virtualenvs/df/lib/python3.11/site-packages/scipy.libs/libopenblasp-r0-23e5df77.3.21.dev.so
        version: 0.3.21.dev
threading_layer: pthreads
   architecture: Prescott
0.0.1.dev0
```
```

**Comment by jeromedockes** [comment]
the problem happens when we try to check if the extracted features (eg year, month, etc.) capture all the information in the datetime column, in order to add the time since epoch feature if they don't. to do so we try to floor the datetime to the frequency `extract_until`, which cannot be done for year and month because they don't represent fixed intervals of time.
we could:
- always add the time since epoch whenever `extract_until` is larger than "day", and keep the current logic when we extract up to day or more
- always add the time since epoch by default, and add a parameter to let the user control wether to add it or not ie remove the logic that decides by itself if that column should be added. an advantage is that a user may want that column even if it is redundant

**Comment by LeoGrin** [comment]
#743 fixes this by checking if we need `total_time` (like before) without using the floor function. But I agree that "add a parameter to let the user control wether to add it or not" is perhaps a good idea.
