### ISSUE TITLE
DOC: Example 03 Change graph subtitles

### ISSUE THREAD

**Issue by dcor01** [skrub-data/skrub#799]
### Describe the issue linked to the documentation

Hi, I noticed the graphs in the example 3 under "plotting the prediction", were a bit messy and hard to read. Specifically the x labels on the graphs - See image below

<img width="753" alt="graphs" src="https://github.com/skrub-data/skrub/assets/47591045/6eb6bf78-f8e3-457e-aadc-1dcdba828250">
g…]()

### Suggest a potential alternative/fix

I can change the format of the X-labels of these graphs to make them look nicer :)

**Comment by Vincent-Maladiere** [comment]
Thanks for this issue @dcor01, this example is being revisited in https://github.com/skrub-data/skrub/pull/784 (WIP)!
