### ISSUE TITLE
support python 3.8 & 3.9

### ISSUE THREAD

**Issue by jeromedockes** [skrub-data/skrub#815]
Why is the oldest python version supported by skrub 3.10?
end of support for 3.8 is only [scheduled](https://www.python.org/downloads/) for October 2024 so unless there is a compelling reason not to I think skrub should work on python 3.8
I see that would require changing some of the type annotations, are there other reasons why we chose 3.10?

**Comment by Vincent-Maladiere** [comment]
cc @GaelVaroquaux :)

**Comment by GaelVaroquaux** [comment]
If it's easy to support 3.9 or 3.8 and 3.9, I say that we can go for it. But, honestly, I wouldn't allocate much energy to this for now. We are a bleeding edge package, let's act like one. I'm more interested in moving forward
