### ISSUE TITLE
Test polars support

### ISSUE THREAD

**Issue by TheooJ** [skrub-data/skrub#825]
I’ve been working on testing Polars inputs (partially closing meta-issue https://github.com/skrub-data/skrub/issues/769). I’ve covered all the tests in this PR so I’m closing my other small PRs https://github.com/skrub-data/skrub/pull/785 & https://github.com/skrub-data/skrub/pull/792. `test_table_vectorizer.py` is being reworked so I’ll do this one later.

**Comment by jeromedockes** [comment]
fixed by #826
