### ISSUE TITLE
`get_feature_names_out` returns lists instead of numpy arrays

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#832]
### Problem Description

This issue is very minor. In scikit-learn, calling `get_feature_names_out` from any estimator returns a numpy array, while in skrub it returns a list. It might be worth bringing consistency between the two libraries by outputting numpy arrays in skrub and to limit the potential confusion for our users.
What do @skrub-data/devs think?

### Feature Description

This issue suggests returning a numpy array instead of a list in `get_feature_names_out` of all skrub estimators that implement it.

**Comment by GaelVaroquaux** [comment]
> This issue is very minor. In scikit-learn, calling get_feature_names_out from any estimator returns a numpy array, while in skrub it returns a list. It might be worth bringing consistency between the two libraries by outputting numpy arrays in skrub and to limit the potential confusion for our users.

Sounds good to me

**Comment by jeromedockes** [comment]
fixed by #838
