### ISSUE TITLE
Add a "related projects" section in the documentation

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#865]
### Describe the issue linked to the documentation

[The dirty-cat doc has a related project section](https://dirty-cat.github.io/stable/#related-projects), so we might consider adding one to the skrub doc. It might also feature new projects.

Also, we currently mention it in our README.rst, but this is not reflected in the website link.

### Suggest a potential alternative/fix

Removing the mention in the README.rst.

**Comment by jeromedockes** [comment]
I think I prefer your suggested alternative, as those lists tend to become outdated and it is a bit difficult & arbitrary to decide what should go in the list
