### ISSUE TITLE
Display columns with the HTML representation of the fitted TableVectorizer

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#948]
### Problem Description

When displaying the HTML representation of a fitted TableVectorizer on a Jupyter notebook, it would help to see the names of the columns matching the different fitted transformers. This info would be useful for a quick sanity check and a better understanding of what the TV does, especially for beginners.

### Feature Description

The `ColumnTransformer` from scikit-learn implements this feature. [Reference](https://scikit-learn.org/stable/modules/compose.html#visualizing-composite-estimators)

<img width="383" alt="Screenshot 2024-06-17 at 14 35 39" src="https://github.com/skrub-data/skrub/assets/18560386/4bec9596-5c79-4dde-ad18-2c1e0dd906e8">

**Comment by Shree7676** [comment]
![image](https://github.com/user-attachments/assets/a694aa62-0f3c-4c04-afab-d38717b1a541)

Is this what you are suggesting ? @Vincent-Maladiere

**Comment by Vincent-Maladiere** [comment]
Try the ColumnTransformer from scikit-learn, we would like to see the column names when clicking on the dropdown!

**Comment by Shree7676** [comment]
I would like to work on this

**Comment by jeromedockes** [comment]
fixed in #1093
