### ISSUE TITLE
Port from sckikit-learn the positioning of the example buttons on downloading, jupyter-lite...

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#988]
### Describe the issue linked to the documentation

Scikit-learn now uses the pydata-sphinx-theme, and positions those buttons on the right sidebar. This is easier to see for the user

https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_1_5_0.html#sphx-glr-auto-examples-release-highlights-plot-release-highlights-1-5-0-py
![image](https://github.com/skrub-data/skrub/assets/208217/bd58cb33-800d-4764-8d38-9586a5d62979)

### Suggest a potential alternative/fix

We need to figure out how this was done in scikit-learn :)

**Comment by jeromedockes** [comment]
they are now on the right in the main branch :tada:  ! closing
