### ISSUE TITLE
Jupyter-lite picks up old versions of the examples?

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#989]
### Describe the bug

When I launch Jupyter-lite from https://skrub-data.org/stable/auto_examples/01_encodings.html#sphx-glr-auto-examples-01-encodings-py, I have the impression that I do not see the tabular_learner function that was added to the example

### Steps/Code to Reproduce

Go to https://skrub-data.org/stable/auto_examples/01_encodings.html#sphx-glr-auto-examples-01-encodings-py and start jupyter-lite

### Expected Results

The example with the tabular_learner

### Actual Results

![image](https://github.com/skrub-data/skrub/assets/208217/26b15ef7-f16f-45c5-babc-f8938036619b)

### Versions

```shell
On the stable website
```

**Comment by jeromedockes** [comment]
can you try clearing the browser's cache or opening a "private window"? at some point I had the impression I had the same issue but it was the browser's cache

**Comment by jeromedockes** [comment]
or maybe in jupyterlite, `File > revert to checkpoint`

**Comment by GaelVaroquaux** [comment]
Private window did the trick. You are right that it was on my side. Closing this issue
